version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: database_name
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db/volume:/docker-entrypoint-initdb.d
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my2.cnf
    ports:
      - 23306:3306
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - db
